server:
  port: 8081
  error:
    include-message: always
  servlet:
    context-path: /lira-api

jwt:
  secret: ph0bo$
  expirationMs: 604800000 # 7 days in millisenconds

spring:
  application:
    name: lira

  jpa:
    show-sql: false
    open-in-view: false

  datasource:
    # Local host
    url: jdbc:postgresql://localhost:5432/liradb
    # Mac db
#    url: jdbc:postgresql://192.168.1.16:5432/liradb
    # AWS db
#    url: jdbc:postgresql://13.50.156.119:5432/phobosdb

    # Docker net
#    url: jdbc:postgresql://phobos_db:5432/phobosdb

    username: admin
    password: adm1n
    hikari:
      connection-timeout: 30000
      max-lifetime: 18000000

user:
  image:
    path: /lira/images/users/
    preffix: /images/users/