version: "3.8"

services:
  phobos-api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: phobos-api
    ports:
      - "8081:8081"
    networks:
      - phobos_net
    volumes:
      - /Users/gusty/Documents/phobos/images/users:/phobos/images/users

networks:
  phobos_net:
    external: true

# para lanzarlo -> docker-compose up --build