-- reports.id is smallint GENERATED BY DEFAULT AS IDENTITY.
-- DROP IDENTITY also drops the internal sequence, so we recreate it.
ALTER TABLE reports ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE reports ALTER COLUMN id TYPE integer;
CREATE SEQUENCE reports_id_seq AS integer START WITH 1000;
ALTER TABLE reports ALTER COLUMN id SET DEFAULT nextval('reports_id_seq');
ALTER SEQUENCE reports_id_seq OWNED BY reports.id;

-- Add optional DNI/NIE to patients for report headers
ALTER TABLE patients ADD COLUMN IF NOT EXISTS dni varchar(20);
